.TH "Blockchain_Wahlclient.AlternativeVotingCandidate" 3 "Sat Dec 12 2020" "Blockchain-Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blockchain_Wahlclient.AlternativeVotingCandidate \- User Control to represent a displayable candidate on the AlternativeVotingForm  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetName\fP (string name)"
.br
.ti -1c
.RI "void \fBSetParty\fP (string party)"
.br
.ti -1c
.RI "void \fBSetMax\fP (int max)"
.br
.ti -1c
.RI "int \fBGetRank\fP ()"
.br
.ti -1c
.RI "int \fBGetId\fP ()"
.br
.ti -1c
.RI "void \fBSetId\fP (int id)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Verwendete Ressourcen bereinigen\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "Erforderliche Methode für die Designerunterstützung\&. Der Inhalt der Methode darf nicht mit dem Code-Editor geändert werden\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "System\&.ComponentModel\&.IContainer \fBcomponents\fP = null"
.br
.RI "Erforderliche Designervariable\&. "
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBname\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.NumericUpDown \fBrankChooser\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBparty\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
User Control to represent a displayable candidate on the AlternativeVotingForm 


.SH "Member Function Documentation"
.PP 
.SS "override void Blockchain_Wahlclient\&.AlternativeVotingCandidate\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Verwendete Ressourcen bereinigen\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP True, wenn verwaltete Ressourcen gelöscht werden sollen; andernfalls False\&.
.RE
.PP

.SS "void Blockchain_Wahlclient\&.AlternativeVotingCandidate\&.InitializeComponent ()\fC [private]\fP"

.PP
Erforderliche Methode für die Designerunterstützung\&. Der Inhalt der Methode darf nicht mit dem Code-Editor geändert werden\&. 
.SH "Member Data Documentation"
.PP 
.SS "System\&.ComponentModel\&.IContainer Blockchain_Wahlclient\&.AlternativeVotingCandidate\&.components = null\fC [private]\fP"

.PP
Erforderliche Designervariable\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Blockchain-Client from the source code\&.
