.TH "Blockchain_Wahlclient.Properties" 3 "Mon Dec 14 2020" "Blockchain-Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blockchain_Wahlclient.Properties
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blockchain-Client from the source code\&.
