.TH "Blockchain_Wahlclient" 3 "Mon Dec 14 2020" "Blockchain-Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blockchain_Wahlclient
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlternativeVoting\fP"
.br
.RI "The Form to display Alternative Voting elections "
.ti -1c
.RI "class \fBAlternativeVotingCandidate\fP"
.br
.RI "User Control to represent a displayable candidate on the AlternativeVotingForm "
.ti -1c
.RI "class \fBBackend\fP"
.br
.RI "Class to handle communication with the blockchain backend "
.ti -1c
.RI "class \fBCandidate\fP"
.br
.RI "Class to represent a candidate "
.ti -1c
.RI "class \fBCandidateList\fP"
.br
.RI "Class to represent a list of candidates and to implement functions for the AlternativeVotingForm "
.ti -1c
.RI "class \fBElectionControl\fP"
.br
.RI "User Control that represents a election and can be displayed on the frontend "
.ti -1c
.RI "class \fBElectionPickerForm\fP"
.br
.ti -1c
.RI "class \fBElectionPickerModel\fP"
.br
.RI "Class that implements functions for the \fBElectionPickerForm\fP "
.ti -1c
.RI "class \fBFirstPastThePostForm\fP"
.br
.RI "Form to display the FirstPastThePost voting screen "
.ti -1c
.RI "class \fBFirstPastThePostModel\fP"
.br
.RI "Class to implement functions for the \fBFirstPastThePostForm\fP "
.ti -1c
.RI "class \fBForm1\fP"
.br
.RI "Start Form "
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBStandardVotingCandidate\fP"
.br
.RI "User Control that represents an entry in the list of candidates that can be displayed on a form "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blockchain-Client from the source code\&.
