.TH "blockchain_admintool.startForm" 3 "Mon Dec 14 2020" "Blockchain-Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blockchain_admintool.startForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBbutton1_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbutton1_Click_1\fP (object sender, EventArgs e)"
.br
.RI "'Save election' button click function creates new candidate list with frontend indexes as candidate ids checks user inputs for mistakes calls the createElection function "
.ti -1c
.RI "DateTime \fBGetStartDate\fP ()"
.br
.RI "returns a \&.NET DateTime object for election beginning defined by user converts to universal central time because time functions on the blockchain also use UTC "
.ti -1c
.RI "DateTime \fBGetStopDate\fP ()"
.br
.RI "returns a \&.NET DateTime object for election beginning defined by user converts to universal central time because time functions on the blockchain also use UTC "
.ti -1c
.RI "void \fBaddCand_Click\fP (object sender, EventArgs e)"
.br
.RI "Add candidate button function Adds new Candidate user control on frontend "
.ti -1c
.RI "void \fBreduceCand_Click\fP (object sender, EventArgs e)"
.br
.RI "Takes one candidate user control away from frontend "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "Required method for Designer support - do not modify the contents of this method with the code editor\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "System\&.ComponentModel\&.IContainer \fBcomponents\fP = null"
.br
.RI "Required designer variable\&. "
.ti -1c
.RI "System\&.Windows\&.Forms\&.ComboBox \fBelectionkind_picker\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.FlowLayoutPanel \fBcandList\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel2\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBaddCand\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBreduceCand\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel3\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton1\fP"
.br
.ti -1c
.RI "\fBcandidate\fP \fBcandidate1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel4\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.TextBox \fBadminadress\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DateTimePicker \fBday_start\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DateTimePicker \fBclock_start\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DateTimePicker \fBclock_stop\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DateTimePicker \fBday_stop\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel5\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel6\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel7\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.RichTextBox \fBname\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel8\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel9\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.TextBox \fBbcurl\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel10\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.TextBox \fBcontractAddr\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.NumericUpDown \fBvoterCount\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel11\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.FolderBrowserDialog \fBfileLocPicker\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void blockchain_admintool\&.startForm\&.addCand_Click (object sender, EventArgs e)\fC [private]\fP"

.PP
Add candidate button function Adds new Candidate user control on frontend 
.PP
\fBParameters\fP
.RS 4
\fIsender\fP 
.br
\fIe\fP 
.RE
.PP

.SS "void blockchain_admintool\&.startForm\&.button1_Click_1 (object sender, EventArgs e)\fC [private]\fP"

.PP
'Save election' button click function creates new candidate list with frontend indexes as candidate ids checks user inputs for mistakes calls the createElection function 
.PP
\fBParameters\fP
.RS 4
\fIsender\fP 
.br
\fIe\fP 
.RE
.PP

.SS "override void blockchain_admintool\&.startForm\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "DateTime blockchain_admintool\&.startForm\&.GetStartDate ()\fC [private]\fP"

.PP
returns a \&.NET DateTime object for election beginning defined by user converts to universal central time because time functions on the blockchain also use UTC 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "DateTime blockchain_admintool\&.startForm\&.GetStopDate ()\fC [private]\fP"

.PP
returns a \&.NET DateTime object for election beginning defined by user converts to universal central time because time functions on the blockchain also use UTC 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void blockchain_admintool\&.startForm\&.InitializeComponent ()\fC [private]\fP"

.PP
Required method for Designer support - do not modify the contents of this method with the code editor\&. 
.SS "void blockchain_admintool\&.startForm\&.reduceCand_Click (object sender, EventArgs e)\fC [private]\fP"

.PP
Takes one candidate user control away from frontend 
.PP
\fBParameters\fP
.RS 4
\fIsender\fP 
.br
\fIe\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "System\&.ComponentModel\&.IContainer blockchain_admintool\&.startForm\&.components = null\fC [private]\fP"

.PP
Required designer variable\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Blockchain-Client from the source code\&.
